#!/usr/bin/python3

import re
import argparse
import pysam
import sys
import importlib


def main(argv=None):
	argv=sys.argv
	
	command = argv[1]
	module = importlib.import_module('handle_umis.'+command)
	
	del sys.argv[0]
	module.main(sys.argv)

if __name__=="__main__":
	sys.exit(main())


	
